[package]
name = "covid_19_ecs"
version = "0.2.0"
authors = ["JunkuiZhang <364772080@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sfml = "*"
rand = "*"
rand_distr = "*"
specs = "*"
